// ==UserScript==
// @name Модификация для Поняча: Typo
// @description При нажатии «Alt+T» в поле ввода текст «оттипографится»
// @namespace dast
// @include http://ponyach.ru/*
// @include http://ponya.ch/*
// @include http://ponyach.cf/*
// @include http://ponyach.ga/*
// @include http://ponyach.ml/*
// @version 1.18
// @grant none
// @run-at document-start
// ==/UserScript==

(function (){

var __m;!function(){function G(i){if(s[i])return s[i];throw"Not found: "+i}function I(i){var m=G(i);m._d||(m._a=1,m.g&&m.g().forEach(function(other){if("@"!=other[0]){if(G(other)._a)throw"Cycle: "+i+", "+other;G(other)._d||I(other)}}),m.v&&m.v(),m.i&&m.i(),m._d=1,delete m._a)}var s={},root=0;__m=function(i,m){if(m)s[i]=m();else{for(i in s)G(i).g&&G(i).s(G(i).g().map(function(i){return G("@"==i[0]?i.slice(1):i).e||{}}));for(i in s)I(i)}}}();
__m("TypoLib",function(){function work(text){return core(text)}function check(text){return/[«„→–]/.test(text)}var core;return{e:{work:work,check:check,get core(){return core}},v:function(){core=function(a,d){a=a.replace(/[«„»“]/g,'"').replace(/[–—]/g,"-");for(n in d={"©":/\([cс]\)/gi,"®":/\([rр]\)/gi,"™":/\((tm|тм)\)/gi,"§":/\((ss|пар)\)/gi,"∞":/\((inf|беск|инф)\)/gi,"°":/\^o/gi,"¹":/\^1/gi,"²":/\^2/gi,"³":/\^3/gi,"µ":/\(u\)/gi,"±":/\(\+-\)/gi,"÷":/\(-:-\)/gi,"×":/\([xх]\)/gi,"≠":/\((!=|=\/=)\)/gi,"→":/->/gi,"←":/<-/gi,"$1•$2":/([\n\r])\*(\s)/gi,"$1́":/([eyuioaаеиоуыэюя])['`]/gi,"¼":/\(1\/4\)/gi,"½":/\(1\/2\)/gi,"¾":/\(3\/4\)/gi,"$1–$2":/([0-9])-([0-9])/gi,"$1—$2":/(^|\s)-(\s|$)/gi,"«$1»":/"([a-zа-я0-9]([^"]|"[a-zа-я0-9][^"]*")*)"/gi,"„$1“":/"([a-zа-я0-9]([^"]|"[a-zа-я0-9][^"]*")*)"/gi})a=a.replace(d[n],n);return a}}}});
__m("UserScript",function(){function execRaw(code){var script=document.createElement("script");script.setAttribute("type","application/javascript"),script.textContent=code,document.documentElement.appendChild(script),document.documentElement.removeChild(script)}function exec(fn){execRaw("("+fn+")();")}function call(name){name in window&&"function"==typeof window[name]?window[name]():execRaw(name+"()")}function override(name,fn){name in window&&"function"==typeof window[name]?window[name]=fn:execRaw("window."+name+" = "+fn)}function callback(fn,answer,oneShot,key){key===undefined&&(key="jsx-user-script-temp-"+Math.round(1e16*Math.random()));var temp=document.getElementById(key);temp||(temp=document.documentElement.appendChild(document.createElement("div")),temp.setAttribute("hidden",!0),temp.setAttribute("id",key)),temp.addEventListener("click",function(arg){var value=localStorage[key]&&JSON.parse(localStorage[key]);value&&delete localStorage[key],answer(value),oneShot&&document.documentElement.removeChild(temp)});var callback=function(arg){var key="__INSERT__KEY__HERE__";arg&&(localStorage[key]=JSON.stringify(arg)),document.getElementById(key).click()};execRaw(("("+fn+")("+callback+");").replace("__INSERT__KEY__HERE__",key))}function onload(callback){/interactive|complete/.test(document.readyState)?callback():document.addEventListener("DOMContentLoaded",callback)}return{e:{execRaw:execRaw,exec:exec,call:call,override:override,callback:callback,onload:onload}}});
__m("Observer",function(){function observe(callback){new(window.MutationObserver||window.WebKitMutationObserver)(function(arg){var target,temp;if(arg)for(var i=0;i<arg.length;i++)if(temp=arg[i].target.parentNode,target){if(temp!=temp){target=undefined;break}}else target=temp;callback(target||document,arg)}).observe(document,{subtree:!0,attributes:!0})}var UserScript;return{e:{observe:observe},g:function(){return["UserScript"]},s:function(__){UserScript=__[0]}}});
__m("DastMod",function(){function register(name,version,options,help){if(registered)throw"Already registered";try{var dastMods=JSON.parse(localStorage[key])||{}}catch(e){var dastMods={}}dastMods[name]&&dastMods[name].version==version||(dastMods[name]={version:version,options:options,help:help}),dastMods[name].date=+new Date,localStorage[key]=JSON.stringify(dastMods),registered=name}var key,registered;return{e:{get key(){return key},get registered(){return registered},register:register},v:function(){key="dast-modifications"}}});
__m("Typo",function(){function work(){for(var inputs=document.querySelectorAll("textarea:not([typo]), input:not([type]):not([typo]), input[type=text]:not([typo]), input[type=search]:not([typo])"),i=0,input;input=inputs[i];i++)input.setAttribute("typo",!0),input.addEventListener("keyup",function(arg){arg.altKey&&84==arg.keyCode&&(this.value=TypoLib.core(this.value))})}function init(){DastMod.register("Typo","1.18",{},'\r\n			При нажатии «Alt+T» в поле ввода текст «оттипографится».\r\n			<span style="font-size:80%">\r\n			<b>Подробнее:</b></span>'.trim().replace(/\t\t\t/g,"")),document.addEventListener("DOMContentLoaded",work,!1)}var TypoLib,Observer,DastMod;return{i:init,g:function(){return["TypoLib","Observer","DastMod"]},s:function(__){TypoLib=__[0],Observer=__[1],DastMod=__[2]}}});
__m();

})()