// ==UserScript==
// @name Модификация для Поняча: Wrwr
// @description Исправляет расползающиеся посты (те, в которых много текста без переносов)
// @namespace wrwr
// @include http://ponyach.ru/*
// @include http://ponya.ch/*
// @include http://ponyach.cf/*
// @include http://ponyach.ga/*
// @include http://ponyach.ml/*
// @version 0.97
// @grant none
// @run-at document-start
// ==/UserScript==

(function (){

var __m;!function(){function G(i){if(s[i])return s[i];throw"Not found: "+i}function I(i){var m=G(i);m._d||(m._a=1,m.g&&m.g().forEach(function(other){if("@"!=other[0]){if(G(other)._a)throw"Cycle: "+i+", "+other;G(other)._d||I(other)}}),m.v&&m.v(),m.i&&m.i(),m._d=1,delete m._a)}var s={},root=0;__m=function(i,m){if(m)s[i]=m();else{for(i in s)G(i).g&&G(i).s(G(i).g().map(function(i){return G("@"==i[0]?i.slice(1):i).e||{}}));for(i in s)I(i)}}}();
__m("UserScript",function(){function execRaw(code){var script=document.createElement("script");script.setAttribute("type","application/javascript"),script.textContent=code,document.documentElement.appendChild(script),document.documentElement.removeChild(script)}function exec(fn){execRaw("("+fn+")();")}function call(name){name in window&&"function"==typeof window[name]?window[name]():execRaw(name+"()")}function override(name,fn){name in window&&"function"==typeof window[name]?window[name]=fn:execRaw("window."+name+" = "+fn)}function callback(fn,answer,oneShot,key){key===undefined&&(key="jsx-user-script-temp-"+Math.round(1e16*Math.random()));var temp=document.getElementById(key);temp||(temp=document.documentElement.appendChild(document.createElement("div")),temp.setAttribute("hidden",!0),temp.setAttribute("id",key)),temp.addEventListener("click",function(arg){var value=localStorage[key]&&JSON.parse(localStorage[key]);value&&delete localStorage[key],answer(value),oneShot&&document.documentElement.removeChild(temp)});var callback=function(arg){var key="__INSERT__KEY__HERE__";arg&&(localStorage[key]=JSON.stringify(arg)),document.getElementById(key).click()};execRaw(("("+fn+")("+callback+");").replace("__INSERT__KEY__HERE__",key))}function onload(callback){/interactive|complete/.test(document.readyState)?callback():document.addEventListener("DOMContentLoaded",callback)}return{e:{execRaw:execRaw,exec:exec,call:call,override:override,callback:callback,onload:onload}}});
__m("Observer",function(){function observe(callback){new(window.MutationObserver||window.WebKitMutationObserver)(function(arg){var target,temp;if(arg)for(var i=0;i<arg.length;i++)if(temp=arg[i].target.parentNode,target){if(temp!=temp){target=undefined;break}}else target=temp;callback(target||document,arg)}).observe(document,{subtree:!0,attributes:!0})}var UserScript;return{e:{observe:observe},g:function(){return["UserScript"]},s:function(__){UserScript=__[0]}}});
__m("DastMod",function(){function register(name,version,options,help){if(registered)throw"Already registered";try{var dastMods=JSON.parse(localStorage[key])||{}}catch(e){var dastMods={}}dastMods[name]&&dastMods[name].version==version||(dastMods[name]={version:version,options:options,help:help}),dastMods[name].date=+new Date,localStorage[key]=JSON.stringify(dastMods),registered=name}var key,registered;return{e:{get key(){return key},get registered(){return registered},register:register},v:function(){key="dast-modifications"}}});
__m("Wrwr",function(){function $each(query,callback,target){target===undefined&&(target=document);for(var elements=document.querySelectorAll(query),i=0,n=elements.length;n>i;i++)callback.call(elements[i])}function fix(text,long){return long?text.replace(/([^\s]{60})/g,"$1​"):text.replace(/([^\s]{30})/g,"$1​")}function work(node){var childs=node.childNodes,child;"DIV"==node.tagName&&"white-space: pre !important;font-family: monospace !important;"==node.getAttribute("style")&&node.setAttribute("style","white-space:pre-wrap;font-family:monospace;");for(var i=0,n=childs.length;n>i;i++)child=childs[i],child.nodeType==TEXT_NODE?child.textContent=fix(child.textContent,"A"!=node.tagName):work(child)}function update(target,event){event&&1==event.length&&"A"==event[0].target.tagName&&"Автообновление треда"==event[0].target.title&&(target=document);for(var elements=target.querySelectorAll("blockquote:not(.wrwr-fixed)"),i=0,n=elements.length;n>i;i++)elements[i].className=(elements[i].className+" wrwr-fixed").trim(),work(elements[i])}function init(){DastMod.register("Wrwr","0.97",{},"Исправляет расползающиеся посты (те, в которых много текста без переносов)"),update(document),Observer.observe(update)}var Observer,DastMod,TEXT_NODE;return{i:init,g:function(){return["Observer","DastMod"]},s:function(__){Observer=__[0],DastMod=__[1]},v:function(){TEXT_NODE=document.TEXT_NODE}}});
__m();

})()